cursor.execute('insert into Birthdaydecoration values(1,"    " , 5000 )')
cursor.execute("insert into Birthdaydecoration values(2,'' , 6000 )")
cursor.execute("insert into Birthdaydecoration values(3,' ' , 7000 )")
cursor.execute("insert into Birthdaydecoration values(4,'' , 8000 )")
cursor.execute("insert into Birthdaydecoration values(5,'' , 9000 )")
cursor.execute("insert into Birthdaydecoration values(6,' ' , 10000 )")
cursor.execute("insert into Birthdaydecoration values(7,'' , 11000 )")
cursor.execute("insert into Birthdaydecoration values(8,'   ' , 12000 )")
cursor.execute("insert into Birthdaydecoration values(9,' ' , 13000 )")
cursor.execute("insert into Birthdaydecoration values(10,' ' , 14000 )")

cursor.execute('insert into Games values(1,"    " , 500 )')
cursor.execute("insert into Games values(2,'' , 1000 )")
cursor.execute("insert into Games values(3,' ' , 1500 )")
cursor.execute("insert into Games values(4,'' , 1600 )")
cursor.execute("insert into Games values(5,'' , 1700 )")
cursor.execute("insert into Games values(6,' ' , 2000 )")
cursor.execute("insert into Games values(7,'' , 2100 )")
cursor.execute("insert into Games values(8,'   ' , 2500 )")
cursor.execute("insert into Games values(9,' ' , 2600 )")
cursor.execute("insert into Games values(10,' ' , 2600 )")


cursor.execute('insert into Returngifts values(1,"    " , 500 )')
cursor.execute("insert into Returngifts values(2,'' , 1000 )")
cursor.execute("insert into Returngifts values(3,' ' , 1500 )")
cursor.execute("insert into Returngifts  values(4,'' , 1600 )")
cursor.execute("insert into Returngifts  values(5,'' , 1700 )")
cursor.execute("insert into Returngifts values(6,' ' , 2000 )")
cursor.execute("insert into Returngifts values(7,'' , 2100 )")
cursor.execute("insert into Returngifts  values(8,'   ' , 2500 )")
cursor.execute("insert into Returngifts  values(9,' ' , 2600 )")
cursor.execute("insert into Returngifts values(10,' ' , 2600 )")



cursor.execute('insert into Haldidecoration values(1,"    " , 500 )')
cursor.execute("insert into Haldidecoration values(2,'' , 1000 )")
cursor.execute("insert into Haldidecoration values(3,' ' , 1500 )")
cursor.execute("insert into Haldidecoration values(4,'' , 1600 )")
cursor.execute("insert into Haldidecoration values(5,'' , 1700 )")
cursor.execute("insert into Haldidecoration values(6,' ' , 2000 )")
cursor.execute("insert into Haldidecoration values(7,'' , 2100 )")
cursor.execute("insert into Haldidecoration values(8,'   ' , 2500 )")
cursor.execute("insert into Haldidecoration values(9,' ' , 2600 )")
cursor.execute("insert into Haldidecoration values(10,' ' , 2600 )")


cursor.execute('insert into Sangeetdecoration values(1,"    " , 500 )')
cursor.execute("insert into Sangeetdecoration values(2,'' , 1000 )")
cursor.execute("insert into Sangeetdecoration values(3,' ' , 1500 )")
cursor.execute("insert into Sangeetdecoration values(4,'' , 1600 )")
cursor.execute("insert into Sangeetdecoration values(5,'' , 1700 )")
cursor.execute("insert into Sangeetdecoration values(6,' ' , 2000 )")
cursor.execute("insert into Sangeetdecoration values(7,'' , 2100 )")
cursor.execute("insert into Sangeetdecoration values(8,'   ' , 2500 )")
cursor.execute("insert into Sangeetdecoration values(9,' ' , 2600 )")
cursor.execute("insert into Sangeetdecoration values(10,' ' , 2600 )")





cursor.execute('insert into Mehandidecoration values(1,"    " , 500 )')
cursor.execute("insert into Mehandidecoration values(2,'' , 1000 )")
cursor.execute("insert into Mehandidecoration values(3,' ' , 1500 )")
cursor.execute("insert into Mehandidecoration values(4,'' , 1600 )")
cursor.execute("insert into Mehandidecoration values(5,'' , 1700 )")
cursor.execute("insert into Mehandidecoration values(6,' ' , 2000 )")
cursor.execute("insert into Mehandidecoration values(7,'' , 2100 )")
cursor.execute("insert into Mehandidecoration values(8,'   ' , 2500 )")
cursor.execute("insert into Mehandidecoration values(9,' ' , 2600 )")
cursor.execute("insert into Mehandidecoration values(10,' ' , 2600 )")


cursor.execute('insert into Receptiondecoration values(1,"    " , 500 )')
cursor.execute("insert into Receptiondecoration values(2,'' , 1000 )")
cursor.execute("insert into Receptiondecoration values(3,' ' , 1500 )")
cursor.execute("insert into Receptiondecoration values(4,'' , 1600 )")
cursor.execute("insert into Receptiondecoration values(5,'' , 1700 )")
cursor.execute("insert into Receptiondecoration values(6,' ' , 2000 )")
cursor.execute("insert into Receptiondecoration values(7,'' , 2100 )")
cursor.execute("insert into Receptiondecoration values(8,'   ' , 2500 )")
cursor.execute("insert into Receptiondecoration values(9,' ' , 2600 )")
cursor.execute("insert into Receptiondecoration values(10,' ' , 2600 )")


cursor.execute('insert into Weddingdecoration values(1,"    " , 500 )')
cursor.execute("insert into Weddingdecoration values(2,'' , 1000 )")
cursor.execute("insert into Weddingdecoration values(3,' ' , 1500 )")
cursor.execute("insert into Weddingdecoration values(4,'' , 1600 )")
cursor.execute("insert into Weddingdecoration values(5,'' , 1700 )")
cursor.execute("insert into Weddingdecoration values(6,' ' , 2000 )")
cursor.execute("insert into Weddingdecoration values(7,'' , 2100 )")
cursor.execute("insert into Weddingdecoration values(8,'   ' , 2500 )")
cursor.execute("insert into Weddingdecoration values(9,' ' , 2600 )")
cursor.execute("insert into Weddingdecoration values(10,' ' , 2600 )")

cursor.execute('insert into Preweddingphotoshoot values(1,"    " , 500 )')
cursor.execute("insert into Preweddingphotoshoot values(2,'' , 1000 )")
cursor.execute("insert into Preweddingphotoshoot values(3,' ' , 1500 )")
cursor.execute("insert into Preweddingphotoshoot values(4,'' , 1600 )")
cursor.execute("insert into Preweddingphotoshoot values(5,'' , 1700 )")
cursor.execute("insert into Preweddingphotoshoot values(6,' ' , 2000 )")
cursor.execute("insert into Preweddingphotoshoot values(7,'' , 2100 )")
cursor.execute("insert into Preweddingphotoshoot values(8,'   ' , 2500 )")
cursor.execute("insert into Preweddingphotoshoot values(9,' ' , 2600 )")
cursor.execute("insert into Preweddingphotoshoot values(10,' ' , 2600 )")



cursor.execute('insert into Postweddingphotoshoot values(1,"    " , 500 )')
cursor.execute("insert into Postweddingphotoshoot values(2,'' , 1000 )")
cursor.execute("insert into Postweddingphotoshoot values(3,' ' , 1500 )")
cursor.execute("insert into Postweddingphotoshoot values(4,'' , 1600 )")
cursor.execute("insert into Postweddingphotoshoot values(5,'' , 1700 )")
cursor.execute("insert into Postweddingphotoshoot values(6,' ' , 2000 )")
cursor.execute("insert into Postweddingphotoshoot values(7,'' , 2100 )")
cursor.execute("insert into Postweddingphotoshoot values(8,'   ' , 2500 )")
cursor.execute("insert into Postweddingphotoshoot values(9,' ' , 2600 )")
cursor.execute("insert into Postweddingphotoshoot values(10,' ' , 2600 )")

cursor.execute('insert into Preweddingvideoshoot values(1,"    " , 500 )')
cursor.execute("insert into Preweddingvideoshoot values(2,'' , 1000 )")
cursor.execute("insert into Preweddingvideoshoot values(3,' ' , 1500 )")
cursor.execute("insert into Preweddingvideoshoot values(4,'' , 1600 )")
cursor.execute("insert into Preweddingvideoshoot values(5,'' , 1700 )")
cursor.execute("insert into Preweddingvideoshoot values(6,' ' , 2000 )")
cursor.execute("insert into Preweddingvideoshoot values(7,'' , 2100 )")
cursor.execute("insert into Preweddingvideoshoot values(8,'   ' , 2500 )")
cursor.execute("insert into Preweddingvideoshoot values(9,' ' , 2600 )")
cursor.execute("insert into Preweddingvideoshoot values(10,' ' , 2600 )")

cursor.execute('insert into Postweddingvideoshoot values(1,"    " , 500 )')
cursor.execute("insert into Postweddingvideoshoot values(2,'' , 1000 )")
cursor.execute("insert into Postweddingvideoshoot values(3,' ' , 1500 )")
cursor.execute("insert into Postweddingvideoshoot values(4,'' , 1600 )")
cursor.execute("insert into Postweddingvideoshoot values(5,'' , 1700 )")
cursor.execute("insert into Postweddingvideoshoot values(6,' ' , 2000 )")
cursor.execute("insert into Postweddingvideoshoot values(7,'' , 2100 )")
cursor.execute("insert into Postweddingvideoshoot values(8,'   ' , 2500 )")
cursor.execute("insert into Postweddingvideoshoot values(9,' ' , 2600 )")
cursor.execute("insert into Postweddingvideoshoot values(10,' ' , 2600 )")

